version: "3.1"

services:
  prueba1_db:
    image: mysql:5.7
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: prueba1_db
      MYSQL_ROOT_USER: PRUEBA1
      MYSQL_USER: PRUEBA1
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_PASSWORD: 123456
